services:
  otel-collector:
    image: otel/opentelemetry-collector:0.106.0
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./observability/otel-collector.yaml:/etc/otel-collector.yaml:ro
    ports:
      - "4318:4318"
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment: [COLLECTOR_OTLP_ENABLED=true]
    ports:
      - "16686:16686"
    restart: unless-stopped
